### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'`

### ISSUE THREAD

**Issue by AlizaminJ** [osmno/school2osm#2]
I get typeerror, any idea how to fix it?

```
`Reading data ... 3322 schools
Converting to file 'skoler.osm' ...

3321 /mnt/c/Users/alja/Downloads/school2osm/school2osm.py:149: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  encoded_key = cgi.escape(key.encode('utf-8'), True)
Traceback (most recent call last):
  File "/mnt/c/Users/alja/Downloads/school2osm/school2osm.py", line 280, in <module>
    make_osm_line("amenity", "school")
  File "/mnt/c/Users/alja/Downloads/school2osm/school2osm.py", line 149, in make_osm_line
    encoded_key = cgi.escape(key.encode('utf-8'), True)
  File "/home/alja/miniconda3/lib/python3.7/cgi.py", line 998, in escape
    s = s.replace("&", "&amp;") # Must be done first!
TypeError: a bytes-like object is required, not 'str'`
```

P.S Urllib2 is depreciated. I replaced it with urllib.request.

**Comment by ghost** [comment]
You have to use python2

On May 13, 2020 11:32:33 AM UTC, Alizamin Jafarli <notifications@github.com> wrote:
>I get typeerror, any idea how to fix it?
>
>`Reading data ... 3322 schools
>Converting to file 'skoler.osm' ...
>
>3321 /mnt/c/Users/alja/Downloads/school2osm/school2osm.py:149:
>DeprecationWarning: cgi.escape is deprecated, use html.escape instead
>  encoded_key = cgi.escape(key.encode('utf-8'), True)
>Traceback (most recent call last):
>File "/mnt/c/Users/alja/Downloads/school2osm/school2osm.py", line 280,
>in <module>
>    make_osm_line("amenity", "school")
>File "/mnt/c/Users/alja/Downloads/school2osm/school2osm.py", line 149,
>in make_osm_line
>    encoded_key = cgi.escape(key.encode('utf-8'), True)
> File "/home/alja/miniconda3/lib/python3.7/cgi.py", line 998, in escape
>    s = s.replace("&", "&amp;") # Must be done first!
>TypeError: a bytes-like object is required, not 'str'`
>
>
>P.S Urllib2 is depreciated. I replaced it with urllib.request.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/osmno/school2osm/issues/2

/f

**Comment by AlizaminJ** [comment]
Thanks!
